<?php


/**
 * This class adds structure of 'tibia_banishment' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jun 20 23:47:37 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class BanishmentMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.BanishmentMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(BanishmentPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(BanishmentPeer::TABLE_NAME);
		$tMap->setPhpName('Banishment');
		$tMap->setClassname('Banishment');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('CHARACTER_ID', 'CharacterId', 'INTEGER', 'tibia_character', 'ID', false, null);

		$tMap->addColumn('BANISHED_UNTIL', 'BanishedUntil', 'TIMESTAMP', false, null);

		$tMap->addColumn('BANISHED_FOR_ID', 'BanishedForId', 'INTEGER', false, null);

		$tMap->addColumn('BANISHED_AT', 'BanishedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('LEVEL', 'Level', 'INTEGER', false, null);

	} // doBuild()

} // BanishmentMapBuilder
