generator:
  class: sfPropelGenerator
  param:
    model_class:           NewsCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news_category
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        display:      [=name, slug]
        peer_method:  doSelectWithI18n
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
