### character rules ###

character_search:
  url:    /:sf_culture/search
  param:  { module: character, action: index }
  requirements:
    sf_culture: (?:hu|en)
                  
character_show:
  url:      /:sf_culture/character/:slug
  class:    sfPropelRoute
  options:  { model: Character, type: object }
  param:    { module: character, action: show } 
  requirements:
    sf_culture: (?:hu|en)
    
character_addlvlup:
  url:      /:sf_culture/character/:slug/addlevelup/:lvlupid
  param:    { module: character, action addLvlUp }
  requirements:
    sf_culture: (?:hu|en)
    lvlupid:  \d+
    
character_botters:
  url:      /:sf_culture/botters
  param:    { module: character, action: botters }    

character_botters_for_server:
  url:      /:sf_culture/botters/:server
  param:    { module: character, action: botters }

character_hackers:
  url:      /:sf_culture/hackers
  param:    { module: character, action: hackers }

character_hackers_for_server:
  url:      /:sf_culture/hackers/:server
  param:    { module: character, action: hackers }

character_acctraders:
  url:      /:sf_culture/acctraders
  param:    { module: character, action: acctraders }

character_acctraders_for_server:
  url:      /:sf_culture/acctraders/:server
  param:    { module: character, action: acctraders }
    
character_advancedsearch:
  url:    /:sf_culture/search/character/advanced
  param:  { module: character, action: advancedSearch }
  requirements:
    sf_culture: (?:hu|en)
    
character_feed:
  url:     /feed/character/:slug
  class:   sfPropelRoute
  options: { model: Character, type: object }
  param:   { module: feed, action: character }    

### guild rules ###  
  
guild_index:
  url:   /:sf_culture/guilds
  param: { module: guild, action: index }
  requirements:
    sf_culture: (?:hu|en)

guild_index_for_server:
  url:   /:sf_culture/guilds/:server
  param: { module: guild, action: index }
  requirements:
    sf_culture: (?:hu|en)

guild_show:
  url:     /:sf_culture/guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: guild, action: show }
  requirements:
    sf_culture: (?:hu|en)

guild_feed:
  url:     /feed/guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: feed, action: guild }

  
### calculator rules ###

calculator_level:
  url:    /:sf_culture/calculator/level
  param:  { module: calculator, action: level }
  requirements:
    sf_culture: (?:hu|en)
  
calculator_stamina:
  url:    /:sf_culture/calculator/stamina
  param:  { module: calculator, action: stamina }
  requirements:
    sf_culture: (?:hu|en)
    
calculator_blessing:
  url:    /:sf_culture/calculator/blessing
  param:  { module: calculator, action: blessing }
  requirements:
    sf_culture: (?:hu|en)
  
### sfguard routes ###

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }  
  
### rules that don't fit any other category :) ###  
  
house_show:
  url:    /house/:server/:slug
  param:  { module: house, action: show }
  requirements:
    server: \w+
    slug:   \w+  
  
localized_homepage:
  url:  /:sf_culture/
  param:  { module: general, action: homepage }
  requirements:
    sf_culture: (?:hu|en)

change_language:
  url:   /change_language
  param: { module: general, action: changeLanguage }
    
# default rules
homepage:
  url:   /
  param: { module: general, action: homepage }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
