### character rules ###

character_search:
  url:    /search
  param:  { module: character, action: index }
                  
character_show:
  url:      /character/:slug
  class:    sfPropelRoute
  options:  { model: Character, type: object }
  param:    { module: character, action: show } 
    
character_addlvlup:
  url:      /character/:slug/addlevelup/:lvlupid
  param:    { module: character, action addLvlUp }
  requirements:
    lvlupid:  \d+
    
character_botters:
  url:      /botters
  param:    { module: character, action: botters }    

character_botters_for_server:
  url:      /botters/:server
  param:    { module: character, action: botters }

character_hackers:
  url:      /hackers
  param:    { module: character, action: hackers }

character_hackers_for_server:
  url:      /hackers/:server
  param:    { module: character, action: hackers }

character_acctraders:
  url:      /acctraders
  param:    { module: character, action: acctraders }

character_acctraders_for_server:
  url:      /acctraders/:server
  param:    { module: character, action: acctraders }
    
character_advancedsearch:
  url:      /search/character/advanced
  param:    { module: character, action: advancedSearch }
    
character_feed:
  url:     /feed/character/:slug
  class:   sfPropelRoute
  options: { model: Character, type: object }
  param:   { module: feed, action: character }    
  
character_banfeed:
  url:   /feed/banishment/:reason/:server
  param:  { module: feed, action: banishment }
  requirements:
    reason: (?:botters|acctraders|hackers)

### guild rules ###  
  
guild_index:
  url:   /guilds
  param: { module: guild, action: index }

guild_index_for_server:
  url:   /guilds/:server
  param: { module: guild, action: index }

guild_show:
  url:     /guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: guild, action: show }

guild_feed:
  url:     /feed/guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: feed, action: guild }

### news rules ###

news_index:
  url:    /news/:page
  param:  { module: news, action: index, page: 1 }
  requirements:
    page: \d+
  
news_show:
  url:    /news/:id/:slug
  class:  sfPropelRoute
  param:  { module: news, action: show }
  options:  { model: News, type: object, method: doSelectOneForRoute }
  requirements:
    id: \d+
    
news_feed:
  url:    /feed/news
  param:  { module: feed, action: news }
  
### calculator rules ###

calculator_level:
  url:    /calculator/level
  param:  { module: calculator, action: level }
  
calculator_stamina:
  url:    /calculator/stamina
  param:  { module: calculator, action: stamina }
    
calculator_blessing:
  url:    /calculator/blessing
  param:  { module: calculator, action: blessing }
  
calculator_mlvl:
  url:    /calculator/mlvl
  param:  { module: calculator, action: mlvl }  
  
calculator_soul:
  url:    /calculator/soul
  param:  { module: calculator, action: soul }  
  
### sfguard routes ###

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }  
  
### rules that don't fit any other category :) ###  
  
last_update:
  url:    /lastupdates
  param:  { module: general, action: lastUpdate }  
  
house_show:
  url:    /house/:server/:slug
  param:  { module: house, action: show }
  requirements:
    server: \w+
    slug:   \w+  
  
# default rules
homepage:
  url:   /
  param: { module: news, action: index }

### OLD RULES BELOW, DO NOT MODIFY ###

### character rules ###

character_search_old:
  url:    /:sf_culture/search
  param:  { module: character, action: index }
  requirements:
    sf_culture: (?:hu|en)
                  
character_show_old:
  url:      /:sf_culture/character/:slug
  class:    sfPropelRoute
  options:  { model: Character, type: object }
  param:    { module: character, action: show } 
  requirements:
    sf_culture: (?:hu|en)
    
character_addlvlup_old:
  url:      /:sf_culture/character/:slug/addlevelup/:lvlupid
  param:    { module: character, action addLvlUp }
  requirements:
    sf_culture: (?:hu|en)
    lvlupid:  \d+
    
character_botters_old:
  url:      /:sf_culture/botters
  param:    { module: character, action: botters }    

character_botters_for_server_old:
  url:      /:sf_culture/botters/:server
  param:    { module: character, action: botters }

character_hackers_old:
  url:      /:sf_culture/hackers
  param:    { module: character, action: hackers }

character_hackers_for_server_old:
  url:      /:sf_culture/hackers/:server
  param:    { module: character, action: hackers }

character_acctraders_old:
  url:      /:sf_culture/acctraders
  param:    { module: character, action: acctraders }

character_acctraders_for_server_old:
  url:      /:sf_culture/acctraders/:server
  param:    { module: character, action: acctraders }
    
character_advancedsearch_old:
  url:    /:sf_culture/search/character/advanced
  param:  { module: character, action: advancedSearch }
  requirements:
    sf_culture: (?:hu|en)
    
character_feed_old:
  url:     /feed/character/:slug
  class:   sfPropelRoute
  options: { model: Character, type: object }
  param:   { module: feed, action: character }    
  
character_banfeed_old:
  url:   /feed/banishment/:reason/:server
  param:  { module: feed, action: banishment }
  requirements:
    reason: (?:botters|acctraders|hackers)

### guild rules ###  
  
guild_index_old:
  url:   /:sf_culture/guilds
  param: { module: guild, action: index }
  requirements:
    sf_culture: (?:hu|en)

guild_index_for_server_old:
  url:   /:sf_culture/guilds/:server
  param: { module: guild, action: index }
  requirements:
    sf_culture: (?:hu|en)

guild_show_old:
  url:     /:sf_culture/guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: guild, action: show }
  requirements:
    sf_culture: (?:hu|en)

guild_feed_old:
  url:     /feed/guild/:slug
  class:   sfPropelRoute
  options: { model: Guild, type: object }
  param:   { module: feed, action: guild }

  
### calculator rules ###

calculator_level_old:
  url:    /:sf_culture/calculator/level
  param:  { module: calculator, action: level }
  requirements:
    sf_culture: (?:hu|en)
  
calculator_stamina_old:
  url:    /:sf_culture/calculator/stamina
  param:  { module: calculator, action: stamina }
  requirements:
    sf_culture: (?:hu|en)
    
calculator_blessing_old:
  url:    /:sf_culture/calculator/blessing
  param:  { module: calculator, action: blessing }
  requirements:
    sf_culture: (?:hu|en)
  
localized_homepage_old:
  url:  /:sf_culture/
  param:  { module: general, action: homepage }
  requirements:
    sf_culture: (?:hu|en)

# default rules

homepage_old:
  url:   /
  param: { module: general, action: homepage }
