generator:
  class: sfPropelGenerator
  param:
    model_class:           News
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          news
    with_propel_route:     1

    config:
      actions: ~
      fields:  
        category_id:  { label: Category }
        newscategory: { label: Category }
        sfGuardUser:  { label: Author }
        user_id:      { label: Author }
      list:    
        batch_actions:  {}
        display:      [=title, sfGuardUser, created_at, newscategory]
        max_per_page: 20
        peer_method:  doSelectJoinAllWithI18N
        sort:         [created_at, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
