<?php
// auto-generated by sfViewConfigHandler
// date: 2009/06/14 00:03:23
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('vary', 'Accept-Language', false);
  $response->addMeta('title', 'Magyar Tibia rajongói oldal', false, false);
  $response->addMeta('description', 'Tibia statisztikák | Tibia statistics', false, false);
  $response->addMeta('keywords', 'tibia statistics hungary secura guardia', false, false);
  $response->addMeta('language', 'hu', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('custom-theme/jquery-ui-1.7.1.custom.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('jquery-1.3.2.min.js', '', array ());
  $response->addJavascript('jquery.dataTables.min.js', '', array ());
  $response->addJavascript('jquery-ui-1.7.1.custom.min.js', '', array ());


