<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/06/14 00:03:18
return array(
'character_search' => new sfRoute('/:sf_culture/search', array (
  'module' => 'character',
  'action' => 'index',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'character_show' => new sfPropelRoute('/:sf_culture/character/:slug', array (
  'module' => 'character',
  'action' => 'show',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
  'model' => 'Character',
  'type' => 'object',
)),
'character_addlvlup' => new sfRoute('/:sf_culture/character/:slug/addlevelup/:lvlupid', array (
  'module' => 'character',
  'action' => 'addLvlUp',
), array (
  'sf_culture' => '(?:hu|en)',
  'lvlupid' => '\\d+',
), array (
)),
'character_botters' => new sfRoute('/:sf_culture/botters', array (
  'module' => 'character',
  'action' => 'botters',
), array (
), array (
)),
'character_botters_for_server' => new sfRoute('/:sf_culture/botters/:server', array (
  'module' => 'character',
  'action' => 'botters',
), array (
), array (
)),
'character_hackers' => new sfRoute('/:sf_culture/hackers', array (
  'module' => 'character',
  'action' => 'hackers',
), array (
), array (
)),
'character_hackers_for_server' => new sfRoute('/:sf_culture/hackers/:server', array (
  'module' => 'character',
  'action' => 'hackers',
), array (
), array (
)),
'character_acctraders' => new sfRoute('/:sf_culture/acctraders', array (
  'module' => 'character',
  'action' => 'acctraders',
), array (
), array (
)),
'character_acctraders_for_server' => new sfRoute('/:sf_culture/acctraders/:server', array (
  'module' => 'character',
  'action' => 'acctraders',
), array (
), array (
)),
'character_advancedsearch' => new sfRoute('/:sf_culture/search/character/advanced', array (
  'module' => 'character',
  'action' => 'advancedSearch',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'character_feed' => new sfPropelRoute('/feed/character/:slug', array (
  'module' => 'feed',
  'action' => 'character',
), array (
), array (
  'model' => 'Character',
  'type' => 'object',
)),
'guild_index' => new sfRoute('/:sf_culture/guilds', array (
  'module' => 'guild',
  'action' => 'index',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'guild_index_for_server' => new sfRoute('/:sf_culture/guilds/:server', array (
  'module' => 'guild',
  'action' => 'index',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'guild_show' => new sfPropelRoute('/:sf_culture/guild/:slug', array (
  'module' => 'guild',
  'action' => 'show',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
  'model' => 'Guild',
  'type' => 'object',
)),
'guild_feed' => new sfPropelRoute('/feed/guild/:slug', array (
  'module' => 'feed',
  'action' => 'guild',
), array (
), array (
  'model' => 'Guild',
  'type' => 'object',
)),
'calculator_level' => new sfRoute('/:sf_culture/calculator/level', array (
  'module' => 'calculator',
  'action' => 'level',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'calculator_stamina' => new sfRoute('/:sf_culture/calculator/stamina', array (
  'module' => 'calculator',
  'action' => 'stamina',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'calculator_blessing' => new sfRoute('/:sf_culture/calculator/blessing', array (
  'module' => 'calculator',
  'action' => 'blessing',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'house_show' => new sfRoute('/house/:server/:slug', array (
  'module' => 'house',
  'action' => 'show',
), array (
  'server' => '\\w+',
  'slug' => '\\w+',
), array (
)),
'localized_homepage' => new sfRoute('/:sf_culture/', array (
  'module' => 'general',
  'action' => 'homepage',
), array (
  'sf_culture' => '(?:hu|en)',
), array (
)),
'change_language' => new sfRoute('/change_language', array (
  'module' => 'general',
  'action' => 'changeLanguage',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'general',
  'action' => 'homepage',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
